blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/Anasoufkir/smartrh/blob/master/README.md
    about: Consulter la documentation avant d'ouvrir une issue.
