name: Feature request
description: Proposer une nouvelle fonctionnalité
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problème à résoudre
      description: Décrivez le besoin ou la limitation actuelle.
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Solution proposée
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considérées

  - type: dropdown
    id: priority
    attributes:
      label: Priorité estimée
      options:
        - Critique
        - Haute
        - Moyenne
        - Faible
